# Sidebar navigation

- label: 'About'
  items:
    - label: 'Technologies'
      link: '/#technologies'
    - label: 'Tech Stack'
      link: '/#tech-stack'
- label: 'Setup'
  items:
    - label: 'Windows'
      link: '/#windows-requirements'
    - label: 'MacOS'
      link: '/#macos-requirements'
    - label: 'Codebase Structure'
      link: '/#code-base-structure'
    - label: 'Local System Setup'
      link: '/#local-system-setup'
    - label: 'Debugging'
      link: '/#debugging'
- label: 'Features'
  items:
    - label: 'Inventory'
      link: '/features/inventory'
    - label: 'Locations'
      link: '/features/locations'
    - label: 'Pallet'
      link: '/features/pallet'
